### ISSUE TITLE
Custom songs don't load if "+" is in the folder name

### ISSUE THREAD

**Issue by m4t7w** [raineio/Quest-SongCore#17]
I just found out that custom songs don't load (empty map with 0 notes), if there is a "+" in the song's folder name

I tested all the following special characters and they work fine , ( ) [ ] - . ãª¼³° _ and japanese kanji

So it seems to be an issue specifically with the character "+"

**Comment by RedBrumbler** [comment]
that... makes no sense lol? is this a linux thing I am unaware of?

**Comment by raineio** [comment]
Would you be able to provide a logcat from SongCore? All you need to run is `adb logcat | Select-String "songcore"` (provided you're on Windows.)

**Comment by RedBrumbler** [comment]
turns out it's something we carried over from songloader

https://github.com/raineio/Quest-SongCore/blob/be3869160a954b51ddbac5b7c521e04af887cad7/src/Hooks/SongLoadingHooks.cpp#L240

**Comment by RedBrumbler** [comment]
okay I just tested, removing that replace() doesn't fix it, there's just actually a problem with folder names that contain a `+`, we might actually just not be able to have that be a thing? not sure

**Comment by RedBrumbler** [comment]
yeah I've been doing some testing, and I am kind of stumped, it just isn't able to load songs that have `+` in the folder name at all (PC might have the same problem?)

**Comment by RedBrumbler** [comment]
the way this is going I might have to just make songcore ignore folder names that contain a `+` to prevent people from seeing broken songs, but that's not the best solution, alternatively we can rename folders that contain `+` to just be a _

**Comment by RedBrumbler** [comment]
After messing around a bit I found that just straight up escaping the url breaks things because / is escaped in the url by the game. I just reimplemented escaping paths and didn't escape / and that makes things work!

**Comment by RedBrumbler** [comment]
[give this build a shot](https://github.com/raineio/Quest-SongCore/actions/runs/8633534113/artifacts/1401925508) and see if it solves the problem for you

**Comment by RedBrumbler** [comment]
no problem! I hope this fixes some other maps that were behaving weird
