### ISSUE TITLE
cant update song core 

### ISSUE THREAD

**Issue by Cbassishim** [raineio/Quest-SongCore#30]
im trying to play beat saber and it keeps crashing for some reason

**Comment by raineio** [comment]
Without any actual information on your game version, mod version nor any logs, I am unable to provide support, or fix the problem.

**Comment by raineio** [comment]
Closing due to lack of information and communication. Please hit up quest-help in the Beat Saber Modding Group if you need help solving your problem.

**Comment by Nitai610** [comment]
btw I have this issue too

**Comment by Nitai610** [comment]
in 1.36.1 and 1.36.2 it just crashes the game but I dont know if its from songcore

**Comment by raineio** [comment]
As I said in an earlier comment, I need logs. If this leads to nowhere, I'm locking the issue.

**Comment by Nitai610** [comment]
ill show you the logs on 1.37 once songcore is updated because rn im on 1.37

**Comment by Nitai610** [comment]
[infoDump.zip](https://github.com/user-attachments/files/15686807/infoDump.zip)
As I said ^^

**Comment by raineio** [comment]
@Nitai610 This doesn't help me at all. Locking due to unrelated issues.
